name: Delete Untagged Docker Images

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every minute
  workflow_dispatch:

jobs:
  delete-untagged:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete untagged Docker images
        uses: actions/delete-package-versions@v5
        with:
            token: ${{ secrets.PAT_TOKEN }} #${{ secrets.GITHUB_TOKEN }}

