name: Delete Package Versions

on:
  push:
    branches:
      - dev # or specify the branch you want to monitor
  workflow_dispatch:

jobs:
  delete-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete package versions
        uses: actions/delete-package-versions@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          package-name: ${{ github.repository }}
          owner: ${{ github.repository_owner }}
          num-old-versions-to-keep: 0


